AWSTemplateFormatVersion: 2010-09-09
Description: Stack para observabilidade na AWS

Resources:

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Habilita acesso ao servidor
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22 # SSH
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 80 # Nginx
          ToPort: 80
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 3000 # Grafana
          ToPort: 3000
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 8080 # Cadvisor
          ToPort: 8080
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 9000 # Prometheus
          ToPort: 9000
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 9091 # OpenWeather
          ToPort: 9091
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 9093 # AlertManager
          ToPort: 9093
          CidrIp: 0.0.0.0/0


  MyContainer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0fc5d935ebf8bc3bc
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref MySecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo -i
          apt-get update -y
          apt-get install -y docker.io
          usermod -aG docker ubuntu
          systemctl enable docker
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

          cd ~

          curl -L "https://github.com/GabrielPauloMai/observability-OpenWeather/archive/master.tar.gz" | tar -xz --strip-components=2 "observability-OpenWeather-master/cloudformation"

          sudo docker-compose up -d

          

          
          
  
Outputs:
  InstanceIp:
    Description: IP da instancia
    Value: !GetAtt MyContainer.PublicIp
    Export:
      Name: InstanceIp