AWSTemplateFormatVersion: 2010-09-09
Description: Stack para observabilidade na AWS

Resources:

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Habilita acesso ao servidor
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22 # SSH
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 80 # Nginx
          ToPort: 80
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 3000 # Grafana
          ToPort: 3000
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 8080 # Cadvisor
          ToPort: 8080
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 9090 # Prometheus
          ToPort: 9090
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 9000 # Graylog
          ToPort: 9000
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 9091 # OpenWeather
          ToPort: 9091
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 9092 # OpenWeather
          ToPort: 9092
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 9095 # OpenWeather
          ToPort: 9095
          CidrIp: 0.0.0.0/0


        - IpProtocol: tcp
          FromPort: 9093 # AlertManager
          ToPort: 9093
          CidrIp: 0.0.0.0/0


  MyContainer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-008d819eefb4b5ee4
      InstanceType: t2.medium
      SecurityGroupIds:
        - !Ref MySecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo -i
          apt-get update -y
          apt-get install -y docker.io
          usermod -aG docker ubuntu
          systemctl enable docker
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

          cd ~

          curl -L "https://github.com/GabrielPauloMai/observability-OpenWeather/archive/master.tar.gz" | tar -xz --strip-components=2 "observability-OpenWeather-master/cloudformation"

          sudo sysctl -w vm.max_map_count=262144

          echo "INSTANCE_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)" > .env

          sudo docker-compose --env-file .env up -d


